[package]
name = "mbrot"
version = "0.2.0"
edition = "2024"
authors = ["Logan-010"]
description = "A program to generate random and customizable mandelbrot fractals."

[dependencies]
clap = { version = "4.6.0", features = ["derive"] }
fastrand = "2.4.1"
image = { version = "0.25.10", default-features = false, features = ["png"] }
rayon = { version = "1.11.0", default-features = false }

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
strip = true
debug = false
incremental = false
rpath = false
overflow-checks = false
